# Generated by Django 3.2 on 2022-03-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='appoved',
            new_name='approved',
        ),
    ]
